/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  EulerAngles.c
 *  model: 8RT-FLEX68-D_transient
 *  expmt: 8RT-FLEX68-D_transient
 *  date:  August 19, 2014
 *  time:  1:35:00 pm
 *  user:  Norwegian University of Science and Technology 
 *  from:  20-sim 4.4 Student License
 *  build: 4.4.1.4356
 **********************************************************/

/*****************************************************************************
--------------------------------------------------------------------------

 Copyright � 1995-2007 Controllab Products B.V. All Rights Reserved.

             www.controllab.nl
               www.20sim.com

 Authors: Frank Groen
--------------------------------------------------------------------------
 Description:

 Contains code for converting between different angle representations
 all 24 different kind of Euler angles
 Quaternions and H-Matrices and Rotation Matrices
--------------------------------------------------------------------------
******************************************************************************/

