/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  motionprofiles.c
 *  model: 8RT-FLEX68-D_transient
 *  expmt: 8RT-FLEX68-D_transient
 *  date:  August 19, 2014
 *  time:  1:35:00 pm
 *  user:  Norwegian University of Science and Technology 
 *  from:  20-sim 4.4 Student License
 *  build: 4.4.1.4356
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

