/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Mon Sep  8 13:42:35 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void ThdynCVConv_Outputs_wrapper(real_T *p,
                          real_T *T,
                          real_T *F,
                          real_T *V ,
			   const real_T *xC,
                          const real_T  *fs)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
p[0] = xC[0];
T[0] = xC[1];
F[0] = xC[3] / (xC[2] - xC[3]) / fs[0];
V[0] = xC[4];
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}

/*
  *  Derivatives function
  *
  */
void ThdynCVConv_Derivatives_wrapper(const real_T *dm,
                          const real_T *dE,
                          const real_T *dmf,
                          const real_T *dV,
                          const real_T *p,
                          const real_T *T,
                          const real_T *F,
                          const real_T *V,
                          real_T *dx ,
                          real_T *xC, 
                          const real_T  *fs,  const int_T  p_width0,
                          const real_T  *p0,  const int_T  p_width1,
                          const real_T  *T0,  const int_T  p_width2,
                          const real_T  *F0,  const int_T  p_width3,
                           const real_T *V0, const int_T  p_width4)
{
/* %%%-SFUNWIZ_wrapper_Derivatives_Changes_BEGIN --- EDIT HERE TO _END */
real_T pTemp, TTemp, FTemp, dF, m, mf, ma, Vtemp;
real_T D;
real_T R, h, s, u, RF, RP, RT, uF, uP, uT, Cp, Cv, K; 

real_T u1, u2;
real_T a11, a12, a21, a22;

pTemp = xC[0];
TTemp = xC[1];
m = xC[2];
mf = xC[3];
Vtemp = xC[4];
ma = m - mf;
FTemp = mf / ma / fs[0];
dF = (dmf[0]*m - dm[0]*mf)/(fs[0]*pow(ma,2));

GetThdynCombGasZach(pTemp, TTemp, FTemp, &R, &h, &s, &u, &RF, &RP, &RT, 
        &uF, &uP, &uT, &Cp, &Cv, &K);


u1 = 1/R*RF*dF + dm[0]/m - dV[0]/Vtemp;
u2 = dE[0] - m*uF*dF - u*dm[0];
D = m*(1/pTemp*uT + 1/TTemp*uP - 1/R*(RP*uT +RT*uP));
a11 = m*uT/D;       a12 = (1/TTemp+1/R*RT)/D;
a21 = -m*uP/D;      a22 = (1/pTemp-1/R*RP)/D;

dx[0] = a11*u1 + a12*u2;
dx[1] = a21*u1 + a22*u2;
dx[2] = dm[0];
dx[3] = dmf[0];
dx[4] = dV[0];
/* %%%-SFUNWIZ_wrapper_Derivatives_Changes_END --- EDIT HERE TO _BEGIN */
}