/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmextps.h
 *  subm:  EngineControlSystem
 *  model: 8RT-FLEX68-D_transient
 *  expmt: 8RT-FLEX68-D_transient
 *  date:  August 19, 2014
 *  time:  1:35:00 pm
 *  user:  Norwegian University of Science and Technology 
 *  from:  20-sim 4.4 Student License
 *  build: 4.4.1.4356
 **********************************************************/

#ifndef XX_MEXTPS_H
#define XX_MEXTPS_H

/* macro definition to get the current simulation time.
 * probably the double is not necessary.
 * use a global structure here which must be given the correct
 * value when this function is called.
 */
#define xx_time (XXDouble)ssGetT(MyS)
#define xx_major   ssIsMajorTimeStep(MyS)

#endif

